### ISSUE TITLE
Add Pending bookings termination

### ISSUE THREAD

**Issue by kirillta** [happy-travel/uwajima#32]
We need to add a **180 seconds** termination for bookings in Pending status because there are a number of situations when Pending lasts too long to hold a customer (24 hours for instance).

The service must try to cancel a booking after 180 seconds in Pending status. 

Two options:
Cancellation succeeds. The booking transfers to Rejected** status.
Cancellation fails. The booking transfers to MCN.

**Before the deployment we need to inform our API-Suppliers about this logic.

**Comment by timur-mut** [comment]
test

**Comment by timur-mut** [comment]
We have a problem that we do not notify the suppliers in any way if the booking status changes to `rejected`.
We have agreed on two strategies for the implementation of this task:
1) Perform an additional investigation of the behavior of each supplier in order to find out how to reject bookings in the `Pending` status
2) Try to cancel the booking, if it is not possible to cancel, or the booking is on deadline, then change the status to `MCN`.
